### ISSUE TITLE
QueryBuilderJS 'NOT group' plugin not working

### ISSUE THREAD

**Issue by dlopeza** [fourlabsldn/QBJSParserBundle#12]
I wish this feature could work:
https://querybuilder.js.org/plugins.html#not-group

In the js, not: true is passed but It´s not been parsed to the DQL

without NOT:

Query:
```
{"condition":"AND","rules":[{
"id":"empresa.siglas","field":"empresa.siglas","type":"string","input":"checkbox","operator":"equal","value":["XXX"]}],"not":false,"valid":true}
```
QueryString (from Debug):
`"SELECT object, object_empresa FROM AppBundle\Entity\Agente object  LEFT JOIN object.empresa object_empresa WHERE ( object_empresa.siglas = ?0 ) "
`
with NOT checked:
Query:
```
{"condition":"AND","rules":[{
"id":"empresa.siglas","field":"empresa.siglas","type":"string","input":"checkbox","operator":"equal","value":["XXX"]}],"not":true,"valid":true}
```
QueryString (from Debug):
`"SELECT object, object_empresa FROM AppBundle\Entity\Agente object  LEFT JOIN object.empresa object_empresa WHERE ( object_empresa.siglas = ?0 ) "
`

The DQL seems to be the same, despite the "not": truefrom the JS

**Comment by galeaspablo** [comment]
@dlopeza as I mentioned in the other thread, this is the repository for the symfony bundle. Your problem is in the dependency, not in this bundle. Can you please file this under https://github.com/fourlabsldn/QBJSParser where I'm a maintainer, and I'll have a look?

**Comment by dlopeza** [comment]
Ops! my mistake... i did it twice, sorry
