### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by cjsfj** [fourlabsldn/QBJSParserBundle#6]
Greetings -

Is this bundle in a place to be considered as production-ready? If so, would it be possible to add a release to the project? 

Just wanted to kindof get a state of the project.

Thanks!

CJ

**Comment by galeaspablo** [comment]
Yes, will add a release soon. Following semantic versioning, it will have be as 0.x.

**Comment by jonny-no1** [comment]
https://github.com/fourlabsldn/QBJSParserBundle/releases/tag/v0.1.0
